version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: neo4j:5.26.10-community-bullseye
    restart: unless-stopped
    volumes:
      - neo4j-data:/data/db
    environment:
      - NEO4J_AUTH=neo4j/neo4j


volumes:
  neo4j-data: